#:kivy 1.4

<ScoundrelGame>:    
    rows: 6
    Label:
        text: ""
        size_hint: None, .2
    Label:
        size_hint: 1, .25
        font_size: 70  
        text: "SCOUNDREL"
    AnchorLayout:
        anchor_x: "center"
        size_hint: 1, .1
        GridLayout:
            size_hint: .2, .8
            rows: 4
            cols: 2
            Label:
                text: "Health"
            Label:
                id: health
                text: "20/20"
            Label:
                text: "Weapon"
            Label:
                id: weapon
                text: "None"
            Label:
                text: "Deck"
            Label:
                id: deck
                text: "44"
    AnchorLayout:
        anchor_x: "center"
        size_hint: 1, .5
        GridLayout:
            size_hint: .5, .8
            rows: 1
            cols: 4
            Button:
                id: c1
                text: "c1"
                on_press: root.card(1)
            Button:
                id: c2
                text: "c2"
                on_press: root.card(2)
            Button:
                id: c3
                text: "c3"
                on_press: root.card(3)
            Button:
                id: c4
                text: "c4"
                on_press: root.card(4)
    AnchorLayout:
        anchor_x: "center"
        size_hint: 1, .1
        Button:
            size_hint: .1, .5
            text: "Run!"
    Label:
        size_hint: None, .2
        text: ""

