#:kivy 1.4
#:import Factory kivy.factory.Factory

<ScoundrelGame>:    
    rows: 6
    Label:
        text: ""
        size_hint: None, .2
    Label:
        size_hint: 1, .25
        font_size: 70  
        text: "SCOUNDREL"
    AnchorLayout:
        anchor_x: "center"
        size_hint: 1, .1
        GridLayout:
            size_hint: .2, .8
            rows: 4
            cols: 2
            Label:
                text: "Health"
            Label:
                id: health
                text: "20/20"
            Label:
                text: "Weapon"
            Label:
                id: weapon
                text: "None"
            Label:
                text: "Cards Remaining"
            Label:
                id: deck
                text: "44"
    AnchorLayout:
        anchor_x: "center"
        size_hint: 1, .5
        GridLayout:
            size_hint: .6, .8
            rows: 1
            cols: 4
            CardButton:
                id: c1
                on_press: root.card(1)
            CardButton:
                id: c2
                on_press: root.card(2)
            CardButton:
                id: c3
                on_press: root.card(3)
            CardButton:
                id: c4
                on_press: root.card(4)
    AnchorLayout:
        anchor_x: "center"
        size_hint: 1, .1
        Button:
            id: run_away
            size_hint: .1, .5
            text: "Run!"
            on_press: root.run_away()
    AnchorLayout:
        size_hint: 1, .2
        anchor_x: "right"
        Button:
            size_hint: .1, 1
            text: 'Help'
            on_release: Factory.HelpPopup().open()


<CardButton@ButtonBehavior+Image>
    allow_stretch: True
    source: "images/cards/card-back1.png"

<HelpPopup@Popup>:
    auto_dismiss: False
    title: "Scoundrel Help"
    GridLayout:
        rows: 7
        cols: 1
        Label:
            text: "SCOUNDREL SOLITARE CARD GAME"
            font_size: 40
            size_hint: .8, .1
        Label:
            text: 'Each "room" of the dungeon you must select a card.\nIts behaviour matches its suit You start with 20 life and you must clear every room of the dungeon.'
            size_hint: .8, .1
        GridLayout:
            rows: 3
            cols: 2
            size_hint: .8, .4
            GridLayout:
                rows: 1
                cols: 2
                Image:
                    source: "images/cards/card-clubs-2.png"
                Image:
                    source: "images/cards/card-spades-2.png"
            Label:
                text: "Clubs/Spades: A monster! If you attack it, it will deal its value in damage to you"
            Image:
                source: "images/cards/card-hearts-2.png"
            Label:
                text: "Hearts: A health potion! You'll immediately heal its value"
            Image:
                source: "images/cards/card-diamonds-2.png"
            Label:
                text: "Diamonds: A weapon! You'll equip this weapon (replacing any existing one)"
        Label:
            size_hint: .8, .15
            text: "When you choose to fight with your weapon, you subtract its value from the monster's damage.\nHowever, you can only use the weapon to fight monsters which are weaker than the last monster you fought with that weapon."
        Label:
            size_hint: .8, .15
            text: "You can choose to run from a room, placing the room cards on the bottom of the deck and drawing four new ones.\nYou cannot run twice in a row!"
                
        Button:
            size_hint: .8, .1
            text: 'Close'
            on_release: root.dismiss()

<GameEndPopup@Popup>:
    auto_dismiss: False
    title: "Game Over"
    GridLayout:
        rows: 2
        cols: 1
        Label:
            text: "Game over"
            size_hint: .8, .9

        Button:
            size_hint: .8, .1
            text: 'Close'
            on_release: root.dismiss()
